### ISSUE TITLE
Request - Dictionary Editor Scrollbar and Keys

### ISSUE THREAD

**Issue by mighele** [old-account-392754/StenoLite#1]
Scrollbar on the dictionary editor and page-up / page-down and arrow keys working

**Comment by old-account-392754** [comment]
Unfortunately, due to the way the underlying data is represented, there is no way to add a scroll bar and keep the program responsive (because I cannot quickly access the absolute position of items in the dictionary; I can only look them up and then walk from one item to the next or previous one; so getting the item at a certain distance from the start means walking the whole dictionary from the start).  I can, however, easily add page up and page down, and they will be in the next release (0.8.2+).  Also the mouse wheel is already enabled for much the same reasons (because the up/down buttons are cumbersome).
